language: java
jdk:
  - oraclejdk7

env:
 global:
   - secure: "DLP7iWpMgK3EhamOQ8SHoAUEJP82xbzzocGPa5c9Li8dTF96ugfFspvKtKKdzPsQelIgggliw2nFktEkN7PODaoee6jbYaXNgSEBkbFHRuYTIy9ZahoIVJ13Zz/FZYi3woDjXd5kKcekGOUPZ8rXeouUNayTd7lPlkdbccPX4nsjVAVObkik9Fh+Qr3nPHA7X8FE3x13FtuiKXHZ73iLzE/OOQkwv2ANv5YuYG6ZYjP7pvA9lBAI8IbUNYJlTZ3QMqVH3arnD3rmGLjBJIx8EGTgTdVBbZMLaT5DwdPi5gWwx0d6bGyTCKdJ6/jnXDmysRpCFzwyM1QGZOqsY0QyskDAxa06sjkHj7xEcBuA5VLbkv+K0bwYy2E48Y/dXf9A3Td15hop1GkvsbU0rT5N9/UL17OoYGuTi2SM08OBOVI66EtEml9rLIlsPJxHuejzwPZeiy33uZ35cO96C4xwC1XlrxqJMhZ/aF/dN+U+9onV0PZ5XDa2UeEoH9llIEDDVyiK2y11xEX04dT6/6h/97y9fwFime4wTNbZ57/R7DP6O54qb8g/aIG5liPJD0ClWYiyRmRnE4RFNuhoY5JzGLJRTwg9X/gr6x06DknNg4b05S16t3lncuIOBwaHi8HpQccTnhIeLpLJPKq23RtiR29wgxP9O8ZYjL0gXdMwWt4="
   - secure: "AkVcwTHvjbyNl/K2+IX/Xhjbp976Bw60sZztU733G7PpZWF9UpwhB5zHAF3MfGzYVy/hSC0HUxO8kxkom0JutulxKLVkkGBG0VZqbP7WIMUzqBxc1LwFVGbsY5NuTqdHF711TIxzOwUcz6PpH38a01AaUBBNiNZ1MH0h/cHPlcAW+NkVa601Eb2th5zaa39PhfEpeIBS4Hty9ZJWEweFWu4NmKSO1NLHaQXiG9SJnQhzjYKHFOVcXwVP0XsnQ4Rt1CFtFO0OOwF6oBo5xWksgCNDM8uLKvimLhpgem6jPsFiRiwIPYmb6hmydcp7Jdd03Axja6H8c/2Ry+0fW118+27oVYMNDjD9MGXwb6jl9xE17RlcZHd8c9leIIOGxtzWggGcDkhDlGMOjgqmRwiklE8p4J0BMvjmvdNxoAfrVpT+Bd+7Fqif9fGrLiPOWWIz6r0+x0KrtYiVrMFI8efl4sc/wVMjKlruuRHu7GJLhrIHI2hsW9/V/8M2j/7PgUiYhP97xeb4FgKSSIVCnXNYqb2ZYd1pr0BapTxwYQU6vLtY32Zm52mMD1fi8PwRAOWExMCCT9vSnwEohkRzjy0AykLwd7muMsJWkQxEq2bMNT/1M4AM3uep1iUaK93/rTKsGnnGJxO1JFjMpVNtT4RhTegHgo4rEMndZWzl85YLPhI="
   - TARGET: ftp://ftp.goko.fr//www/download/
   - UPDATE_FOLDER: update
   - updateRepository: true
   - updateBinaries: false
   - gokoVersion: 0.3.0

cache:
  directories:
    - '$HOME/.m2/repository'
    
before_script:
  - cd org.goko.build.aggregator
 
script: 
  - mvn clean verify

after_failure:
   - "curl --ftp-create-dirs -T ../org.goko.build.parent/target/site/surefire-report.html -u $VAR1:$VAR2 $TARGET/$gokoVersion/surefire.html"
  #- "cat ../org.goko.build.parent/target/site/surefire-report.html"
  #TODO add surefire report exports

deploy:
  provider: bintray
  file: "/home/travis/build/cncgoko/Goko/bintray_descriptor.json"
  on: gcode-migration
  user:
    secure: "G2usVWNBz0jgF94xCLUYS5goZ4Qkalm8nGaJVcbaVgAOnnt1+atCGqVfh7CxTdYOBqD2z0kZOEZ+DEfywo/3Eew8P92I0XAJmw4uXSYhXMCr4N8GED6bUMYCVOnoTHMifK1GiBjznAjIp++Uu6xFD0d+YBskECp+os/ZvA27UYp2OT4iknkDpkPATEJjDHRgzwf+F8E8b6YPXwA2AErVzdJ5kj6PqO9jsbQ8CJJgCNPGp/YxZ+2cFIJzuTcvViWwUjTsBfSRm5NhtnHmkii+INIfFnQSt7wZgcaA0pPuoGb85BCS8OGGrHDcinAVe/eL1wUITdoq876SdwteDQfq4fqThbNvaq/uxi6spURFWkE+5JVwF/XoHlEp+tRL9jKgo2sgHYBfNvI54cPznEae5dB/vgUWPAfm+UYLNiDXsgrll9lONZrAjelqb97VJq8h2G7CpjY3RmXYOR9jVeMKRS06Zpf1RXeL/GIBO5ITK/Omcv3pDG1vJ7lJ+TTScZ46tQ7Eiddnr5CdiVr3ILAJ/s8U1HNPTOV+a90YwmuIGdKYFXXFDObP8MLt0lHhEcECsa2mKMF0Dx1vQ/jX5fPiDHqVxULhLh+upZvaMfg0Va0bSuNkmUfRj/5g56wthvFDk1ZTluc8XwvG64kfBXQueC3w1RItBuPZAdi91l0br8E="
  key: 
    secure: "aovA/OwB1eJ/qtj6xagkb2hk+vgCkobPRFl9bP+fWOmKZ1riWOZvXYAraG8lpIjqKQQPZUiCv/R0nJuJjnp5jk22GhiXF7KhlDG+SlaN3gLd2lTEXYbHYGdUo06OceN5BfcW/AlEY9w10NDGvl7O1t9Wt0HAHei+OdPljN/xeqgbldK+1eN31ouqmnLhDJw/KA7ljYAoFkJNisq4qba7WaglwlFeqDaq5H5uYqs29y+aJyoOYS9/3zAvPuV5j/x/TdInUgOa+KUuCHI6W49sU6b2mTzBMgW5RaaqGLjPwttfSg6qVxjOYBNQsWpFwsde8siNMon536AHZjW7a+pJS+UugtnknAy8nL+/856nIWNjqI6Ihk30B7SVDtE/19WnbsfGu57JE4QaofppFL4zmFgK0iiAmY5c4NfPe2C9pEECQbH3bKGgJLZSXQqq1aocEXEhdUoiJlMZwlGxe6dT/AEOiEdmsXe3sH5ntIaZDbcAmVkGO/j1Z6oLmiOo9s4RrquBkFBM+YJKLZWJPE1/cVtcvPUvauv/76nxqGCA8V+jQ2iUQUXWx72xKMmqUDorHForIBONv0/YY7wNCdy9I+u63659S5k2MH84vtReEtUQuGWrUTjlVO7X/K6oxP5Zsza+J1Wy64xr4Jl/BIqdSlM1wvF4EH6eEhdEelgy3Pw="
  dry-run: false
  
after_deploy:
 - chmod a+x ./../deploy.sh
# - ./../deploy.sh
# - cd /home/travis/build/cncgoko/Goko/org.goko.build.product/target/repository
# - "find . -type f -exec curl --ftp-create-dirs -T {} -u $VAR1:$VAR2 $TARGET/"
 #- "curl --ftp-create-dirs -T /home/travis/build/cncgoko/Goko/org.goko.build.product/target/products/org.goko-win32.win32.x86_64.zip -u $VAR1:$VAR2 $TARGET/org.goko-win32.win32.x86_64.zip"
