language: java
jdk:
  - oraclejdk7

env:
 global:
   - secure: "DLP7iWpMgK3EhamOQ8SHoAUEJP82xbzzocGPa5c9Li8dTF96ugfFspvKtKKdzPsQelIgggliw2nFktEkN7PODaoee6jbYaXNgSEBkbFHRuYTIy9ZahoIVJ13Zz/FZYi3woDjXd5kKcekGOUPZ8rXeouUNayTd7lPlkdbccPX4nsjVAVObkik9Fh+Qr3nPHA7X8FE3x13FtuiKXHZ73iLzE/OOQkwv2ANv5YuYG6ZYjP7pvA9lBAI8IbUNYJlTZ3QMqVH3arnD3rmGLjBJIx8EGTgTdVBbZMLaT5DwdPi5gWwx0d6bGyTCKdJ6/jnXDmysRpCFzwyM1QGZOqsY0QyskDAxa06sjkHj7xEcBuA5VLbkv+K0bwYy2E48Y/dXf9A3Td15hop1GkvsbU0rT5N9/UL17OoYGuTi2SM08OBOVI66EtEml9rLIlsPJxHuejzwPZeiy33uZ35cO96C4xwC1XlrxqJMhZ/aF/dN+U+9onV0PZ5XDa2UeEoH9llIEDDVyiK2y11xEX04dT6/6h/97y9fwFime4wTNbZ57/R7DP6O54qb8g/aIG5liPJD0ClWYiyRmRnE4RFNuhoY5JzGLJRTwg9X/gr6x06DknNg4b05S16t3lncuIOBwaHi8HpQccTnhIeLpLJPKq23RtiR29wgxP9O8ZYjL0gXdMwWt4="
   - secure: "AkVcwTHvjbyNl/K2+IX/Xhjbp976Bw60sZztU733G7PpZWF9UpwhB5zHAF3MfGzYVy/hSC0HUxO8kxkom0JutulxKLVkkGBG0VZqbP7WIMUzqBxc1LwFVGbsY5NuTqdHF711TIxzOwUcz6PpH38a01AaUBBNiNZ1MH0h/cHPlcAW+NkVa601Eb2th5zaa39PhfEpeIBS4Hty9ZJWEweFWu4NmKSO1NLHaQXiG9SJnQhzjYKHFOVcXwVP0XsnQ4Rt1CFtFO0OOwF6oBo5xWksgCNDM8uLKvimLhpgem6jPsFiRiwIPYmb6hmydcp7Jdd03Axja6H8c/2Ry+0fW118+27oVYMNDjD9MGXwb6jl9xE17RlcZHd8c9leIIOGxtzWggGcDkhDlGMOjgqmRwiklE8p4J0BMvjmvdNxoAfrVpT+Bd+7Fqif9fGrLiPOWWIz6r0+x0KrtYiVrMFI8efl4sc/wVMjKlruuRHu7GJLhrIHI2hsW9/V/8M2j/7PgUiYhP97xeb4FgKSSIVCnXNYqb2ZYd1pr0BapTxwYQU6vLtY32Zm52mMD1fi8PwRAOWExMCCT9vSnwEohkRzjy0AykLwd7muMsJWkQxEq2bMNT/1M4AM3uep1iUaK93/rTKsGnnGJxO1JFjMpVNtT4RhTegHgo4rEMndZWzl85YLPhI="
   - TARGET: ftp://ftp.goko.fr//www/download/
   - updateRepository: true
   - gokoVersion: 0.0.2

cache:
  directories:
    - '/home/travis/build/cncgoko/Goko/.m2/repository'
    
before_script:
  - cd org.goko.build.aggregator
 
script: 
 - chmod a+x ./../deploy.sh
 - ./../deploy.sh
  #- mvn clean verify

after_failure:
  - "cat ../org.goko.build.parent/target/surefire-reports/*.txt"

#after_success:
 #- chmod a+x ./../deploy.sh
 #- ./../deploy.sh
# - cd /home/travis/build/cncgoko/Goko/org.goko.build.product/target/repository
# - "find . -type f -exec curl --ftp-create-dirs -T {} -u $VAR1:$VAR2 $TARGET/"
 #- "curl --ftp-create-dirs -T /home/travis/build/cncgoko/Goko/org.goko.build.product/target/products/org.goko-win32.win32.x86_64.zip -u $VAR1:$VAR2 $TARGET/org.goko-win32.win32.x86_64.zip"
