language: java
jdk:
  - oraclejdk7


before_script:
  - cd org.goko.build.aggregator
 
script: 
  - mvn clean verify

after_failure:
  - "cat ../org.goko.build.parent/target/surefire-reports/*.txt"
  
after_success:
  - "curl --ftp-create-dirs -T org.goko.build.product/target/products/org.goko-win32.win32.x86_64.zip -u $VAR1:$VAR2 $PATH/org.goko-win32.win32.x86_64.zip"
