language: java
jdk:
  - oraclejdk7
 
before_script:
  - cd org.goko.build.aggregator
 
script: 
  - mvn clean verify -e

after_failure:
  - cat /home/travis/build/cncgoko/Goko/org.goko.controller.tinyg.junit/target/surefire-reports/*.txt
